#ifndef IO_UTILS_H
#define IO_UTILS_H

#include <unistd.h> // read, write
#include <assert.h> // assert
#include <stdint.h> // int32_t
#include <stddef.h> // size_t
#include <vector>
#include <fcntl.h>
#include <cerrno>
#include <cstdio>
#include "../utils.h"
#include <cstring>
#include <sys/socket.h>

using std::vector;

struct Conn
{
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    vector<uint8_t> incoming; // data to be parsed by the application
    vector<uint8_t> outgoing; // responses generated by the application
};

// append to the back
static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len)
{
    buf.insert(buf.end(), data, data + len);
}

// remove from the front
static void buf_consume(std::vector<uint8_t> &buf, size_t n)
{
    buf.erase(buf.begin(), buf.begin() + n);
}

static void fd_set_nb(int fd)
{
    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);
}

static void msg_errno(const char *msg)
{
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void handle_write(Conn *conn)
{
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, conn->outgoing.data(), conn->outgoing.size());
    if (rv < 0)
    {
        if (errno = EAGAIN)
            return;
        msg_errno("write() error");
        conn->want_close = true;
        return;
    }

    // remove written data from 'outgoing'
    buf_consume(conn->outgoing, (size_t)rv);

    // Check: all data written
    if (conn->outgoing.size() == 0)
    {
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
}

static Conn *handle_accept(int listeningFd)
{
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(listeningFd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0)
        return NULL;

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    // create a 'struct Conn'
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true; // read the 1st request.
    return conn;
}

// ex "try_one_request()"
static bool process_message_from_buffer(Conn *conn)
{
    if (conn->incoming.size() < 4) // check if knows the msg size
        return false;              // want read

    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);

    if (len > k_max_msg)
    {
        conn->want_close = true;
        return false; // want close
    }

    if (4 + len > conn->incoming.size()) // checks if msg is completed.
        return false;                    // want read

    // at this point, msg is completed and saved as request.
    const uint8_t *request = &conn->incoming[4];

    // got one request, do some application logic
    printf("client says: len:%d data:%.*s\n",
           len, len < 100 ? len : 100, request);

    // generate the response (echo)
    buf_append(conn->outgoing, (const uint8_t *)&len, 4);
    buf_append(conn->outgoing, request, len);
    // 5. Remove the message from `Conn::incoming`.
    buf_consume(conn->incoming, 4 + len);
    return true; // success
}

static void handle_read(Conn *conn)
{
    // Non-blocking read
    uint8_t buf[64 * 1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv <= 0)
    {
        conn->want_close = true;
        return;
    }
    // 2. Add new data to the `Conn::incoming` buffer.
    buf_append(conn->incoming, buf, (size_t)rv);
    // 3. Try to parse the accumulated buffer.
    // 4. Process the parsed message.
    // 5. Remove the message from `Conn::incoming`.

    while (process_message_from_buffer(conn))
    {
    };

    // Check: has a response
    if (conn->outgoing.size() > 0)
    {
        conn->want_read = false;
        conn->want_write = true;

        return handle_write(conn); // write response
    } // else: want read
}

#endif // IO_UTILS_H