#include <iostream>
#include <vector>
#include <sys/socket.h>
#include <netinet/in.h>
#include <poll.h>
#include <unistd.h>
#include <fcntl.h>
#include <cstring>
#include "../utils.h"
#include <assert.h>

using std::vector;
struct Conn
{
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    vector<uint8_t> incoming; // data to be parsed by the application
    vector<uint8_t> outgoing; // responses generated by the application
};

static void fd_set_nb(int fd)
{
    fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);
}

static Conn *handle_accept(int listeningFd)
{
    // accept
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    int connfd = accept(listeningFd, (struct sockaddr *)&client_addr, &addrlen);
    if (connfd < 0)
        return NULL;

    // set the new connection fd to nonblocking mode
    fd_set_nb(connfd);

    // create a 'struct Conn'
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true; // read the 1st request.
    return conn;
}

// append to the back
static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len)
{
    buf.insert(buf.end(), data, data + len);
}
// remove from the front
static void buf_consume(std::vector<uint8_t> &buf, size_t n)
{
    buf.erase(buf.begin(), buf.begin() + n);
}

// ex "try_one_request()"
static bool process_message_from_buffer(Conn *conn)
{
    if (conn->incoming.size() < 4) // check if knows the msg size
        return false;              // want read

    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);

    if (len > k_max_msg)
    {
        conn->want_close = true;
        return false; // want close
    }

    if (4 + len > conn->incoming.size()) // checks if msg is completed.
        return false;                    // want read

    // at this point, msg is completed and saved as request.
    const uint8_t *request = &conn->incoming[4];

    // got one request, do some application logic
    printf("client says: len:%d data:%.*s\n",
           len, len < 100 ? len : 100, request);

    // generate the response (echo)
    buf_append(conn->outgoing, (const uint8_t *)&len, 4);
    buf_append(conn->outgoing, request, len);
    // 5. Remove the message from `Conn::incoming`.
    buf_consume(conn->incoming, 4 + len);
    return true; // success
}

static void handle_read(Conn *conn)
{
    // Non-blocking read
    uint8_t buf[64 * 1024];
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv <= 0)
    {
        conn->want_close = true;
        return;
    }
    // 2. Add new data to the `Conn::incoming` buffer.
    buf_append(conn->incoming, buf, (size_t)rv);
    // 3. Try to parse the accumulated buffer.
    // 4. Process the parsed message.
    // 5. Remove the message from `Conn::incoming`.

    while (process_message_from_buffer(conn))
    {
    };

    // Check: has a response
    if (conn->outgoing.size() > 0)
    {
        conn->want_read = false;
        conn->want_write = true;

        return handle_write(conn); // write response
    } // else: want read
}

static void handle_write(Conn *conn)
{
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, conn->outgoing.data(), conn->outgoing.size());
    if (rv < 0)
    {
        conn->want_close = true;
        return;
    }

    // remove written data from 'outgoing'
    buf_consume(conn->outgoing, (size_t)rv);

    // Check: all data written
    if (conn->outgoing.size() == 0)
    {
        conn->want_read = true;
        conn->want_write = false;
    } // else: want write
}

int main()
{
    // the listening socket
    int listeningFd = socket(AF_INET, SOCK_STREAM, 0);
    if (listeningFd < 0)
        die("socket()");

    int val = 1;
    setsockopt(listeningFd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));

    // bind
    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = ntohs(1234);
    addr.sin_addr.s_addr = ntohl(0); // wildcard address 0.0.0.0
    int rv = bind(listeningFd, (const sockaddr *)&addr, sizeof(addr));
    if (rv)
        die("bind()");

    fd_set_nb(listeningFd);

    // listen
    rv = listen(listeningFd, SOMAXCONN);
    if (rv)
        die("listen()");

    // a map of all client connections, indexed by fd
    vector<Conn *> fd2conn;

    // The event loop
    vector<struct pollfd> poll_args;
    while (true)
    {
        // prepare the arguments of the poll()
        poll_args.clear();

        // put the listening sockets in the first position
        struct pollfd pfd = {listeningFd, POLLIN, 0};
        poll_args.push_back(pfd);

        // the rest are connection sockets
        for (Conn *conn : fd2conn)
        {
            if (!conn)
                continue;

            struct pollfd pfd = {conn->fd, POLLERR, 0};

            // poll() flags from the application's intent

            /*
                |= is a Logic OR, 0100 | 0001 equals 0101
                Can keep the POLLIN when assign POLLOUT.
                With only =, POLLIN would be removed (if it was assigned before).
            */
            if (conn->want_read)
                pfd.events |= POLLIN;

            if (conn->want_write)
                pfd.events |= POLLOUT;

            poll_args.push_back(pfd);
        }

        // wait for readinesss
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if (rv < 0)
        {
            if (errno == EINTR) // when syscall is aborted by Unix, it returns EINTR. must iterate.
                continue;
            die("poll");
        }

        // handle the listening socket
        if (poll_args[0].revents)
        {
            if (Conn *conn = handle_accept(listeningFd))
            {
                // put it into the map (resize if needed)
                if (fd2conn.size() <= (size_t)conn->fd)
                    fd2conn.resize(conn->fd + 1);
                fd2conn[conn->fd] = conn;
            }
        }

        for (size_t i = 1; i < poll_args.size(); i++)
        {
            uint32_t ready = poll_args[i].revents;
            Conn *conn = fd2conn[poll_args[i].fd];
            // if(ready & POLLIN) handle_read(conn);
            // if(ready & POLLOUT) handle_write(conn);

            if ((ready & POLLERR) || conn->want_close)
            {
                (void)close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }
    return 0;
}